//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NearEvents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAnnouncement
    {
        public tAnnouncement()
        {
            this.tComment = new HashSet<tComment>();
        }
    
        public int id { get; set; }
        public int id_map { get; set; }
        public int id_person { get; set; }
        public Nullable<int> id_category { get; set; }
        public string announce_info { get; set; }
        public Nullable<System.TimeSpan> time_start { get; set; }
        public Nullable<System.TimeSpan> time_end { get; set; }
        public byte[] image { get; set; }
        public string icon { get; set; }
        public Nullable<int> icon_size { get; set; }
        public Nullable<int> time_referans { get; set; }
        public Nullable<int> group { get; set; }
        public Nullable<int> is_right { get; set; }
    
        public virtual tCategory tCategory { get; set; }
        public virtual tMap tMap { get; set; }
        public virtual tPerson tPerson { get; set; }
        public virtual ICollection<tComment> tComment { get; set; }
    }
}
