//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NearEvents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tComment
    {
        public int id { get; set; }
        public int id_person { get; set; }
        public int id_announcement { get; set; }
        public string comment { get; set; }
        public Nullable<int> rate { get; set; }
        public Nullable<int> rate_count { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<bool> inrange { get; set; }
    
        public virtual tAnnouncement tAnnouncement { get; set; }
        public virtual tPerson tPerson { get; set; }
    }
}
