//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NearEvents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPerson
    {
        public tPerson()
        {
            this.tAnnouncement = new HashSet<tAnnouncement>();
            this.tComment = new HashSet<tComment>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public Nullable<int> age { get; set; }
        public string bio { get; set; }
        public byte[] image { get; set; }
        public Nullable<int> person_type { get; set; }
    
        public virtual ICollection<tAnnouncement> tAnnouncement { get; set; }
        public virtual ICollection<tComment> tComment { get; set; }
    }
}
